name: Python UT Check

on:
  pull_request:
    types: [opened, synchronize, reopened, draft]

jobs:
  python-ut-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run UT
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          python3 -m unittest discover -s tests